# SHWD / VOC2028 Kaggle Benchmark

This notebook is a Kaggle wrapper for `kaggle_shwd_baseline.py`. Upload this notebook and the companion script together, attach the VOC2028 dataset, then run the cells in order.

Default behavior is safe: it converts VOC to YOLO and runs a 1-epoch smoke test only. Set `RUN_FULL_TRAINING = True` to train all stable baselines for 100 epochs on Dual T4.

In [1]:
# Optional but recommended on Kaggle. Re-run the kernel after install if Kaggle asks for it.
from pathlib import Path
import sys, subprocess

req_candidates = [Path.cwd() / 'requirements_kaggle.txt', Path('/kaggle/working/requirements_kaggle.txt')]
if Path('/kaggle/input').exists():
    req_candidates.extend(Path('/kaggle/input').rglob('requirements_kaggle.txt'))
req_path = next((p for p in req_candidates if p.exists()), None)
if req_path is not None:
    subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '-U', '-r', str(req_path)], check=True)
else:
    subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '-U', 'ultralytics', 'onnx', 'onnxruntime-gpu', 'pandas', 'albumentations', 'opencv-python-headless'], check=True)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 1.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 23.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 249.8/249.8 MB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 94.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 MB 30.4 MB/s eta 0:00:00

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.39.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
ydata-profiling 4.18.4 requires pandas!=1.4.0,<3.0,>1.5, but you have pandas 3.0.5 which is incompatible.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.12.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
dopamine-rl 4.1.2 requires gym<=0.25.2, but you have gym 0.26.2 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.5 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
db-dtypes 1.5.1 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.5 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.5 which is incompatible.

In [2]:
from pathlib import Path
import os, sys, subprocess, textwrap

DATASET_ROOT = Path('/kaggle/input/datasets/hannhu4002/voc2028/VOC2028')
OUTPUT_DIR = Path('/kaggle/working/SHWD_YOLO')
SCRIPT_NAME = 'kaggle_shwd_baseline.py'

script_candidates = [
    Path('/kaggle/working') / SCRIPT_NAME,
    Path.cwd() / SCRIPT_NAME,
]
for root in [Path('/kaggle/input'), Path('/kaggle/working')]:
    if root.exists():
        script_candidates.extend(root.rglob(SCRIPT_NAME))

SCRIPT_PATH = next((p for p in script_candidates if p.exists()), None)
if SCRIPT_PATH is None:
    raise FileNotFoundError('Upload kaggle_shwd_baseline.py with this notebook, or add it as a Kaggle input dataset.')
print('Using script:', SCRIPT_PATH)
print('Dataset root requested:', DATASET_ROOT)
print('Output dir:', OUTPUT_DIR)

try:
    import torch
    print('CUDA available:', torch.cuda.is_available())
    print('GPU count:', torch.cuda.device_count())
    for i in range(torch.cuda.device_count()):
        print(i, torch.cuda.get_device_name(i))
except Exception as exc:
    print('Torch/GPU check failed:', exc)

Using script: /kaggle/input/datasets/hannhu4002/shwd-benchmark-code/kaggle_shwd_baseline.py
Dataset root requested: /kaggle/input/datasets/hannhu4002/voc2028/VOC2028
Output dir: /kaggle/working/SHWD_YOLO
CUDA available: True
GPU count: 2
0 Tesla T4
1 Tesla T4

## Convert VOC2028 to YOLO

This uses `trainval.txt` for training and `test.txt` for validation/test, keeps `difficult=1` objects, ignores unknown classes, and symlinks images where possible to protect `/kaggle/working` disk space.

In [3]:
cmd = [
    sys.executable, str(SCRIPT_PATH),
    '--mode', 'convert',
    '--dataset-root', str(DATASET_ROOT),
    '--output-dir', str(OUTPUT_DIR),
    '--overwrite',
]
print(' '.join(cmd))
subprocess.run(cmd, check=True)

/usr/bin/python3 /kaggle/input/datasets/hannhu4002/shwd-benchmark-code/kaggle_shwd_baseline.py --mode convert --dataset-root /kaggle/input/datasets/hannhu4002/voc2028/VOC2028 --output-dir /kaggle/working/SHWD_YOLO --overwrite
{
  "dataset_root": "/kaggle/input/datasets/hannhu4002/voc2028/VOC2028",
  "output_dir": "/kaggle/working/SHWD_YOLO",
  "train_images": 6064,
  "test_images": 1517,
  "labels_written": 7581,
  "missing_images": 0,
  "missing_xml": 0,
  "invalid_boxes": 0,
  "ignored_objects": 3,
  "class_counts": {
    "hat": 9044,
    "person": 111514
  },
  "ignored_by_class": {
    "dog": 3
  },
  "dry_run": false
}

CompletedProcess(args=['/usr/bin/python3', '/kaggle/input/datasets/hannhu4002/shwd-benchmark-code/kaggle_shwd_baseline.py', '--mode', 'convert', '--dataset-root', '/kaggle/input/datasets/hannhu4002/voc2028/VOC2028', '--output-dir', '/kaggle/working/SHWD_YOLO', '--overwrite'], returncode=0)

In [4]:
# Inspect conversion outputs. Expected local counts: trainval=6064, test=1517.
!find /kaggle/working/SHWD_YOLO -maxdepth 3 -type f | head -30
!cat /kaggle/working/SHWD_YOLO/conversion_report.json
!head -20 /kaggle/working/SHWD_YOLO/ignored_labels.csv || true

/kaggle/working/SHWD_YOLO/conversion_report.json
/kaggle/working/SHWD_YOLO/shwd.yaml
/kaggle/working/SHWD_YOLO/invalid_annotations.csv
/kaggle/working/SHWD_YOLO/ignored_labels.csv
/kaggle/working/SHWD_YOLO/labels/test/PartA_01638.txt
/kaggle/working/SHWD_YOLO/labels/test/PartA_00338.txt
/kaggle/working/SHWD_YOLO/labels/test/part2_001847.txt
/kaggle/working/SHWD_YOLO/labels/test/part2_001483.txt
/kaggle/working/SHWD_YOLO/labels/test/PartB_00076.txt
/kaggle/working/SHWD_YOLO/labels/test/PartB_01289.txt
/kaggle/working/SHWD_YOLO/labels/test/PartB_02163.txt
/kaggle/working/SHWD_YOLO/labels/test/part2_000571.txt
/kaggle/working/SHWD_YOLO/labels/test/000054.txt
/kaggle/working/SHWD_YOLO/labels/test/part2_000357.txt
/kaggle/working/SHWD_YOLO/labels/test/PartA_00316.txt
/kaggle/working/SHWD_YOLO/labels/test/PartB_02280.txt
/kaggle/working/SHWD_YOLO/labels/test/PartB_00571.txt
/kaggle/working/SHWD_YOLO/labels/test/PartA_01858.txt
/kaggle/working/SHWD_YOLO/labels/test/PartA_01723.txt
/kaggle/working/SHWD_YOLO/labels/test/PartB_00862.txt
/kaggle/working/SHWD_YOLO/labels/test/001503.txt
/kaggle/working/SHWD_YOLO/labels/test/PartA_00318.txt
/kaggle/working/SHWD_YOLO/labels/test/PartB_01861.txt
/kaggle/working/SHWD_YOLO/labels/test/part2_001881.txt
/kaggle/working/SHWD_YOLO/labels/test/PartA_01786.txt
/kaggle/working/SHWD_YOLO/labels/test/part2_001128.txt
/kaggle/working/SHWD_YOLO/labels/test/000332.txt
/kaggle/working/SHWD_YOLO/labels/test/PartB_00338.txt
/kaggle/working/SHWD_YOLO/labels/test/PartB_00318.txt
/kaggle/working/SHWD_YOLO/labels/test/PartB_02041.txt
find: ‘standard output’: Broken pipe
find: write error
{
  "dataset_root": "/kaggle/input/datasets/hannhu4002/voc2028/VOC2028",
  "output_dir": "/kaggle/working/SHWD_YOLO",
  "train_images": 6064,
  "test_images": 1517,
  "labels_written": 7581,
  "missing_images": 0,
  "missing_xml": 0,
  "invalid_boxes": 0,
  "ignored_objects": 3,
  "class_counts": {
    "hat": 9044,
    "person": 111514
  },
  "ignored_by_class": {
    "dog": 3
  },
  "dry_run": false

## Smoke Test

Run a 1-epoch YOLO11n smoke test before spending GPU time on the full tournament.

In [5]:
RUN_SMOKE_TEST = False
if RUN_SMOKE_TEST:
    cmd = [
        sys.executable, str(SCRIPT_PATH),
        '--mode', 'smoke',
        '--dataset-root', str(DATASET_ROOT),
        '--output-dir', str(OUTPUT_DIR),
        '--epochs', '1',
        '--imgsz', '640',
        '--device', '0,1',
        '--workers', '4',
        '--benchmark-repeats', '20',
        '--benchmark-warmup', '5',
    ]
    print(' '.join(cmd))
    subprocess.run(cmd, check=True)

## Full Baseline Tournament

Set `RUN_FULL_TRAINING = True` only after the smoke test succeeds. This trains `yolov8n/s`, `yolov10n/s`, and `yolo11n/s` for 100 epochs.

In [6]:
RUN_FULL_TRAINING = True
if RUN_FULL_TRAINING:
    cmd = [
        sys.executable, str(SCRIPT_PATH),
        '--mode', 'all',
        '--dataset-root', str(DATASET_ROOT),
        '--output-dir', str(OUTPUT_DIR),
        '--epochs', '100',
        '--imgsz', '640',
        '--device', '0,1',
        '--workers', '4',
        '--patience', '50',
        '--benchmark-repeats', '100',
        '--benchmark-warmup', '20',
        '--models', 'yolo11n.pt', 'yolo11s.pt',
    ]
    print(' '.join(cmd))
    subprocess.run(cmd, check=True)

/usr/bin/python3 /kaggle/input/datasets/hannhu4002/shwd-benchmark-code/kaggle_shwd_baseline.py --mode all --dataset-root /kaggle/input/datasets/hannhu4002/voc2028/VOC2028 --output-dir /kaggle/working/SHWD_YOLO --epochs 100 --imgsz 640 --device 0,1 --workers 4 --patience 50 --benchmark-repeats 100 --benchmark-warmup 20 --models yolo11n.pt yolo11s.pt
{
  "dataset_root": "/kaggle/input/datasets/hannhu4002/voc2028/VOC2028",
  "output_dir": "/kaggle/working/SHWD_YOLO",
  "train_images": 6064,
  "test_images": 1517,
  "labels_written": 7581,
  "missing_images": 0,
  "missing_xml": 0,
  "invalid_boxes": 0,
  "ignored_objects": 3,
  "class_counts": {
    "hat": 9044,
    "person": 111514
  },
  "ignored_by_class": {
    "dog": 3
  },
  "dry_run": false
}

=== Training yolo11n.pt for 100 epoch(s) ===
Creating new Ultralytics Settings v0.0.7 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo11n.pt to 'yolo11n.pt': 100% ━━━━━━━━━━━━ 5.4MB 62.8MB/s 0.1s
Ultralytics 8.4.115 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
                                                        CUDA:1 (Tesla T4, 14912MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/working/SHWD_YOLO/shwd.yaml, degrees=0.0, deterministic=True, device=0,1, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.025, hsv_s=0.75, hsv_v=0.45, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.1, mode=train, model=yolo11n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolo11n, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=50, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/kaggle/working/SHWD_YOLO/runs, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/SHWD_YOLO/runs/yolo11n, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=3407, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=4, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 15.9MB/s 0.0s
Overriding model.yaml nc=80 with nc=2

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 23        [16, 19, 22]  1    431062  ultralytics.nn.modules.head.Detect           [2, 16, None, [64, 128, 256]]
YOLO11n summary: 182 layers, 2,590,230 parameters, 2,590,214 gradients, 6.5 GFLOPs

Remapped 1/2 cls head rows from pretrained weights by class name
Transferred 451/499 items from pretrained weights
DDP: debug command /usr/bin/python3 -m torch.distributed.run --nproc_per_node 2 --master_port 29400 /root/.config/Ultralytics/DDP/_temp_drnldgb9136304563978112.py
Ultralytics 8.4.115 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
                                                        CUDA:1 (Tesla T4, 14912MiB)
Overriding model.yaml nc=80 with nc=2
Remapped 1/2 cls head rows from pretrained weights by class name
Transferred 451/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 68.1MB/s 0.1s
AMP: checks passed ✅
WARNING ⚠️ train: Slow image access detected (ping: 0.0±0.0 ms, read: 5.7±2.6 MB/s, size: 70.6 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
train: Scanning /kaggle/working/SHWD_YOLO/labels/train... 6011 images, 0 backgrounds, 53 corrupt: 100% ━━━━━━━━━━━━ 6064/6064 258.1it/s 23.5s
train: /kaggle/working/SHWD_YOLO/images/train/000003.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000003.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000006.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000006.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000007.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000007.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000011.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000011.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000061.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000061.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000068.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000068.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000091.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000091.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000113.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000113.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000153.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000153.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000158.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000158.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000173.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000173.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000177.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000177.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000184.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000184.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000226.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000226.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000267.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000267.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000268.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000268.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000274.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000274.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000284.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000284.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000290.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000290.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000320.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000320.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000393.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000393.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000397.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000397.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000433.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000433.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000458.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000458.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000512.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000512.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000514.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000514.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000528.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000528.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000548.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000548.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000601.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000601.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000686.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000686.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000687.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000687.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000734.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000734.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000738.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000738.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000797.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000797.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000798.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000798.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000799.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000799.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000820.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000820.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000827.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000827.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000909.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000909.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000964.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000964.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000985.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000985.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/001042.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/001042.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/001046.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/001046.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/001150.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/001150.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/001354.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/001354.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/001358.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/001358.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/001386.JPG: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/001386.JPG'
train: /kaggle/working/SHWD_YOLO/images/train/001387.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/001387.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/part2_000609.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/part2_000609.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/part2_000878.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/part2_000878.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/part2_001057.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/part2_001057.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/part2_001363.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/part2_001363.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/part2_001696.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/part2_001696.jpg'
train: New cache created: /kaggle/working/SHWD_YOLO/labels/train.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
WARNING ⚠️ val: Slow image access detected (ping: 0.0±0.0 ms, read: 10.2±6.2 MB/s, size: 100.7 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning /kaggle/working/SHWD_YOLO/labels/test... 1506 images, 0 backgrounds, 11 corrupt: 100% ━━━━━━━━━━━━ 1517/1517 256.4it/s 5.9s
val: /kaggle/working/SHWD_YOLO/images/test/000002.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000002.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/000106.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000106.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/000168.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000168.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/000291.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000291.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/000457.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000457.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/000565.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000565.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/000599.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000599.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/000640.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000640.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/000796.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000796.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/000815.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000815.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/part2_001825.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/part2_001825.jpg'
val: New cache created: /kaggle/working/SHWD_YOLO/labels/test.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001667, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Plotting labels to /kaggle/working/SHWD_YOLO/runs/yolo11n/labels.jpg...
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/SHWD_YOLO/runs/yolo11n
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      1.82G      1.813      1.568      1.123        190        640: 100% ━━━━━━━━━━━━ 376/376 3.5it/s 1:47
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 1.7it/s 28.9s
                   all       1506      24375      0.825      0.718      0.798      0.455


2026-08-04 16:43:35.057785471 [E:onnxruntime:Default, provider_bridge_ort.cc:2395 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1988 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library /usr/local/lib/python3.12/dist-packages/onnxruntime/capi/libonnxruntime_providers_cuda.so with error: libcublasLt.so.13: cannot open shared object file: No such file or directory

2026-08-04 16:43:35.057843888 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1150 CreateExecutionProviderFactoryInstance] Failed to create CUDAExecutionProvider. Require cuDNN 9.* and CUDA 13.*. Please install all dependencies as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

{
  "model": "yolo11n.pt",
  "epochs": 100,
  "run_dir": "/kaggle/working/SHWD_YOLO/runs/yolo11n",
  "best_pt": "/kaggle/working/SHWD_YOLO/runs/yolo11n/weights/best.pt",
  "best_pt_mb": 5.207,
  "map50": 0.9318516549725213,
  "map50_95": 0.6020884383969626,
  "map75": 0.6305960056648201,
  "ap_hat": 0.7152026429708198,
  "ap_person": 0.4889742338231051,
  "ap50_hat": 0.9232600289784385,
  "ap50_person": 0.9404432809666041,
  "precision_hat": 0.9300090008706818,
  "precision_person": 0.9197017605194965,
  "recall_hat": 0.8650575973669775,
  "recall_person": 0.8831927870608528,
  "f1_hat": 0.896358221597683,
  "f1_person": 0.90107761680031,
  "speed_preprocess_ms": 0.6613634402441637,
  "speed_inference_ms": 3.1826775079687426,
  "speed_loss_ms": 0.0015685252362561838,
  "speed_postprocess_ms": 1.3586747802150816,
  "csv_epoch": "100",
  "csv_time": "9240.77",
  "csv_train/box_loss": "1.346",
  "csv_train/cls_loss": "0.54571",
  "csv_train/dfl_loss": "0.95511",
  "csv_metrics/precision(B)": "0.92186",
  "csv_metrics/recall(B)": "0.86919",
  "csv_metrics/mAP50(B)": "0.92838",
  "csv_metrics/mAP50-95(B)": "0.5987",
  "csv_val/box_loss": "1.31983",
  "csv_val/cls_loss": "0.54666",
  "csv_val/dfl_loss": "0.96014",
  "csv_lr/pg0": "3.31733e-05",
  "csv_lr/pg1": "3.31733e-05",
  "csv_lr/pg2": "3.31733e-05",
  "onnx_path": "/kaggle/working/SHWD_YOLO/runs/yolo11n/weights/best.onnx",
  "onnx_mb": 10.076,
  "onnx_provider": "CUDAExecutionProvider",
  "onnx_latency_mean_ms": 68.2158,
  "onnx_latency_p95_ms": 100.3847,
  "onnx_fps_mean": 14.66,
  "onnx_removed_after_benchmark": true,
  "hard_negative_dir": "/kaggle/input/hard-negatives",
  "hard_negative_status": "not_available"
}

=== Training yolo11s.pt for 100 epoch(s) ===
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo11s.pt to 'yolo11s.pt': 100% ━━━━━━━━━━━━ 18.4MB 138.0MB/s 0.1s
Ultralytics 8.4.115 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
                                                        CUDA:1 (Tesla T4, 14912MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/working/SHWD_YOLO/shwd.yaml, degrees=0.0, deterministic=True, device=0,1, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.025, hsv_s=0.75, hsv_v=0.45, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.1, mode=train, model=yolo11s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolo11s, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=50, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/kaggle/working/SHWD_YOLO/runs, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/SHWD_YOLO/runs/yolo11s, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=3407, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=4, workspace=None
Overriding model.yaml nc=80 with nc=2

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    443776  ultralytics.nn.modules.block.C3k2            [768, 256, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    127680  ultralytics.nn.modules.block.C3k2            [512, 128, 1, False]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    345472  ultralytics.nn.modules.block.C3k2            [384, 256, 1, False]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 23        [16, 19, 22]  1    820182  ultralytics.nn.modules.head.Detect           [2, 16, None, [128, 256, 512]]
YOLO11s summary: 182 layers, 9,428,566 parameters, 9,428,550 gradients, 21.7 GFLOPs

Remapped 1/2 cls head rows from pretrained weights by class name
Transferred 499/499 items from pretrained weights
DDP: debug command /usr/bin/python3 -m torch.distributed.run --nproc_per_node 2 --master_port 27108 /root/.config/Ultralytics/DDP/_temp_o201d7i4136304145599232.py
Ultralytics 8.4.115 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
                                                        CUDA:1 (Tesla T4, 14912MiB)
Overriding model.yaml nc=80 with nc=2
Remapped 1/2 cls head rows from pretrained weights by class name
Transferred 499/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 60.2±23.6 MB/s, size: 70.6 KB)
train: Scanning /kaggle/working/SHWD_YOLO/labels/train.cache... 6011 images, 0 backgrounds, 53 corrupt: 100% ━━━━━━━━━━━━ 6064/6064 847.8Mit/s 0.0s
train: /kaggle/working/SHWD_YOLO/images/train/000003.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000003.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000006.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000006.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000007.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000007.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000011.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000011.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000061.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000061.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000068.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000068.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000091.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000091.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000113.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000113.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000153.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000153.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000158.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000158.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000173.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000173.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000177.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000177.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000184.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000184.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000226.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000226.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000267.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000267.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000268.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000268.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000274.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000274.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000284.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000284.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000290.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000290.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000320.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000320.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000393.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000393.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000397.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000397.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000433.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000433.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000458.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000458.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000512.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000512.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000514.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000514.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000528.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000528.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000548.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000548.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000601.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000601.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000686.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000686.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000687.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000687.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000734.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000734.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000738.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000738.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000797.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000797.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000798.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000798.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000799.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000799.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000820.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000820.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000827.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000827.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000909.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000909.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000964.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000964.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/000985.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/000985.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/001042.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/001042.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/001046.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/001046.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/001150.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/001150.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/001354.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/001354.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/001358.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/001358.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/001386.JPG: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/001386.JPG'
train: /kaggle/working/SHWD_YOLO/images/train/001387.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/001387.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/part2_000609.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/part2_000609.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/part2_000878.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/part2_000878.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/part2_001057.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/part2_001057.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/part2_001363.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/part2_001363.jpg'
train: /kaggle/working/SHWD_YOLO/images/train/part2_001696.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/train/part2_001696.jpg'
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 72.4±50.8 MB/s, size: 100.7 KB)
val: Scanning /kaggle/working/SHWD_YOLO/labels/test.cache... 1506 images, 0 backgrounds, 11 corrupt: 100% ━━━━━━━━━━━━ 1517/1517 44.5Mit/s 0.0s
val: /kaggle/working/SHWD_YOLO/images/test/000002.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000002.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/000106.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000106.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/000168.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000168.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/000291.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000291.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/000457.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000457.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/000565.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000565.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/000599.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000599.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/000640.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000640.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/000796.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000796.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/000815.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/000815.jpg'
val: /kaggle/working/SHWD_YOLO/images/test/part2_001825.jpg: ignoring corrupt image/label: [Errno 30] Read-only file system: '/kaggle/working/SHWD_YOLO/images/test/part2_001825.jpg'
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001667, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Plotting labels to /kaggle/working/SHWD_YOLO/runs/yolo11s/labels.jpg...
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/SHWD_YOLO/runs/yolo11s
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      2.62G      1.706       1.05       1.08        190        640: 100% ━━━━━━━━━━━━ 376/376 3.4it/s 1:51
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 48/48 1.7it/s 29.0s
                   all       1506      24375      0.836      0.754      0.814      0.476

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

2026-08-04 19:27:01.495828950 [E:onnxruntime:Default, provider_bridge_ort.cc:2395 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1988 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library /usr/local/lib/python3.12/dist-packages/onnxruntime/capi/libonnxruntime_providers_cuda.so with error: libcublasLt.so.13: cannot open shared object file: No such file or directory

2026-08-04 19:27:01.495915441 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1150 CreateExecutionProviderFactoryInstance] Failed to create CUDAExecutionProvider. Require cuDNN 9.* and CUDA 13.*. Please install all dependencies as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

{
  "model": "yolo11s.pt",
  "epochs": 100,
  "run_dir": "/kaggle/working/SHWD_YOLO/runs/yolo11s",
  "best_pt": "/kaggle/working/SHWD_YOLO/runs/yolo11s/weights/best.pt",
  "best_pt_mb": 18.278,
  "map50": 0.9473794939947808,
  "map50_95": 0.6254145618878485,
  "map75": 0.6609529835806499,
  "ap_hat": 0.7426457636990806,
  "ap_person": 0.5081833600766162,
  "ap50_hat": 0.9405984379974524,
  "ap50_person": 0.9541605499921092,
  "precision_hat": 0.911164585989622,
  "precision_person": 0.9391390506706918,
  "recall_hat": 0.9034558420186506,
  "recall_person": 0.9100342868844143,
  "f1_hat": 0.9072938401298284,
  "f1_person": 0.9243576239233333,
  "speed_preprocess_ms": 0.6181409329339712,
  "speed_inference_ms": 6.52413257703688,
  "speed_loss_ms": 0.0006309090199036793,
  "speed_postprocess_ms": 1.1178316872584988,
  "csv_epoch": "100",
  "csv_time": "9719.71",
  "csv_train/box_loss": "1.27084",
  "csv_train/cls_loss": "0.48635",
  "csv_train/dfl_loss": "0.93734",
  "csv_metrics/precision(B)": "0.92764",
  "csv_metrics/recall(B)": "0.90455",
  "csv_metrics/mAP50(B)": "0.94492",
  "csv_metrics/mAP50-95(B)": "0.62338",
  "csv_val/box_loss": "1.29022",
  "csv_val/cls_loss": "0.5078",
  "csv_val/dfl_loss": "0.95717",
  "csv_lr/pg0": "3.31733e-05",
  "csv_lr/pg1": "3.31733e-05",
  "csv_lr/pg2": "3.31733e-05",
  "onnx_path": "/kaggle/working/SHWD_YOLO/runs/yolo11s/weights/best.onnx",
  "onnx_mb": 36.135,
  "onnx_provider": "CUDAExecutionProvider",
  "onnx_latency_mean_ms": 144.5346,
  "onnx_latency_p95_ms": 150.2963,
  "onnx_fps_mean": 6.92,
  "onnx_removed_after_benchmark": true,
  "hard_negative_dir": "/kaggle/input/hard-negatives",
  "hard_negative_status": "not_available"
}

In [7]:
# Consolidated results.
import pandas as pd
results_csv = OUTPUT_DIR / 'benchmark_results.csv'
if results_csv.exists():
    df = pd.read_csv(results_csv)
    display(df)
    sort_cols = [c for c in ['map50', 'map50_95', 'onnx_fps_mean'] if c in df.columns]
    if sort_cols:
        display(df.sort_values(sort_cols, ascending=[False] * len(sort_cols)).head(10))
else:
    print('No benchmark_results.csv yet.')

,ap50_hat,ap50_person,ap_hat,ap_person,best_pt,best_pt_mb,csv_epoch,csv_lr/pg0,csv_lr/pg1,csv_lr/pg2,...,onnx_removed_after_benchmark,precision_hat,precision_person,recall_hat,recall_person,run_dir,speed_inference_ms,speed_loss_ms,speed_postprocess_ms,speed_preprocess_ms
0,0.923260,0.940443,0.715203,0.488974,/kaggle/working/SHWD_YOLO/runs/yolo11n/weights...,5.207,100,0.000033,0.000033,0.000033,...,True,0.930009,0.919702,0.865058,0.883193,/kaggle/working/SHWD_YOLO/runs/yolo11n,3.182678,0.001569,1.358675,0.661363
1,0.940598,0.954161,0.742646,0.508183,/kaggle/working/SHWD_YOLO/runs/yolo11s/weights...,18.278,100,0.000033,0.000033,0.000033,...,True,0.911165,0.939139,0.903456,0.910034,/kaggle/working/SHWD_YOLO/runs/yolo11s,6.524133,0.000631,1.117832,0.618141

,ap50_hat,ap50_person,ap_hat,ap_person,best_pt,best_pt_mb,csv_epoch,csv_lr/pg0,csv_lr/pg1,csv_lr/pg2,...,onnx_removed_after_benchmark,precision_hat,precision_person,recall_hat,recall_person,run_dir,speed_inference_ms,speed_loss_ms,speed_postprocess_ms,speed_preprocess_ms
1,0.940598,0.954161,0.742646,0.508183,/kaggle/working/SHWD_YOLO/runs/yolo11s/weights...,18.278,100,0.000033,0.000033,0.000033,...,True,0.911165,0.939139,0.903456,0.910034,/kaggle/working/SHWD_YOLO/runs/yolo11s,6.524133,0.000631,1.117832,0.618141
0,0.923260,0.940443,0.715203,0.488974,/kaggle/working/SHWD_YOLO/runs/yolo11n/weights...,5.207,100,0.000033,0.000033,0.000033,...,True,0.930009,0.919702,0.865058,0.883193,/kaggle/working/SHWD_YOLO/runs/yolo11n,3.182678,0.001569,1.358675,0.661363

## RTSP Readiness Template

Kaggle usually cannot access your RTSP cameras. Use this on the deployment PC after selecting the champion `best.pt` or TensorRT engine.

In [8]:
RTSP_TEMPLATE = r'''
from ultralytics import YOLO
model = YOLO('path/to/best.pt')
results = model.predict(
    source='rtsp://USERNAME:REDACTED@camera-ip:554/stream1',
    imgsz=640,
    conf=0.25,
    device=0,
    stream=True,
)
for result in results:
    # Insert alert/dashboard logic here.
    pass
'''
print(RTSP_TEMPLATE)

from ultralytics import YOLO
model = YOLO('path/to/best.pt')
results = model.predict(
    source='rtsp://USERNAME:REDACTED@camera-ip:554/stream1',
    imgsz=640,
    conf=0.25,
    device=0,
    stream=True,
)
for result in results:
    # Insert alert/dashboard logic here.
    pass